"""init schema

Revision ID: 782730bde01e
Revises: 
Create Date: 2026-01-04 20:57:45.557334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782730bde01e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=140), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('pronouns', sa.String(length=40), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('favorite_movie_character', sa.String(length=120), nullable=True),
    sa.Column('favorite_quote', sa.String(length=200), nullable=True),
    sa.Column('current_project', sa.String(length=200), nullable=True),
    sa.Column('current_goal', sa.String(length=200), nullable=True),
    sa.Column('open_to_roles', sa.JSON(), nullable=True),
    sa.Column('university_names', sa.JSON(), nullable=True),
    sa.Column('current_semester', sa.String(length=30), nullable=True),
    sa.Column('current_courses', sa.JSON(), nullable=True),
    sa.Column('clubs', sa.JSON(), nullable=True),
    sa.Column('top_skills', sa.JSON(), nullable=True),
    sa.Column('tools_stack', sa.JSON(), nullable=True),
    sa.Column('is_open_to_recommendations', sa.Boolean(), nullable=False),
    sa.Column('is_hiring', sa.Boolean(), nullable=False),
    sa.Column('favorite_books', sa.JSON(), nullable=True),
    sa.Column('achievements_highlight', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('twitter_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
