"""verification status + verification requests

Revision ID: e4cc50ddcbeb
Revises: 2e0b953a4086
Create Date: 2026-01-07 09:19:16.115547
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "e4cc50ddcbeb"
down_revision: Union[str, Sequence[str], None] = "2e0b953a4086"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # IMPORTANT:
    # Do NOT drop verification_requests here. If Alembic autogenerated that,
    # it means your model wasn't detected at autogenerate time.
    #
    # Fix: keep the table, just add verification columns to entries.

    # ---- education_entries ----
    op.add_column(
        "education_entries",
        sa.Column(
            "verification_status",
            sa.String(),
            nullable=False,
            server_default="VERIFIED",  # existing rows become VERIFIED
        ),
    )
    op.add_column("education_entries", sa.Column("verified_at", sa.DateTime(), nullable=True))
    op.alter_column("education_entries", "verification_status", server_default=None)

    # ---- work_experiences ----
    op.add_column(
        "work_experiences",
        sa.Column(
            "verification_status",
            sa.String(),
            nullable=False,
            server_default="VERIFIED",  # existing rows become VERIFIED
        ),
    )
    op.add_column("work_experiences", sa.Column("verified_at", sa.DateTime(), nullable=True))
    op.alter_column("work_experiences", "verification_status", server_default=None)


def downgrade() -> None:
    # Only remove what this migration added
    op.drop_column("work_experiences", "verified_at")
    op.drop_column("work_experiences", "verification_status")
    op.drop_column("education_entries", "verified_at")
    op.drop_column("education_entries", "verification_status")
